# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherMVP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



  target 'WeatherMVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
